### PR TITLE
Support configuration cache

### PR DESCRIPTION
**Pull request by storytellerF**
related issue #474 #311 

only *samples/compose-resources-gallery* enable configuration cache, because it use parent folder's resource-generator, other sample need moko-resource release new artificat. 

update jetbrains compose,agp,gradle version is necessary on my mac.
>ld: unknown options: -ios_simulator_version_min -sdk_version

>jetbrains compose 1.5.11
agp 8.2.0
gradle 8.2
kotlin 1.9.21

### CODE REVIEW

**Comment by Alex009** [comment]
hi @storytellerF . thanks for PR. but i can't see changes for configuration cache. what exactly was done for configuration cache?

**Comment by storytellerF** [comment]
@Alex009 The main problem is that the task references **SourceSet** which belongs to gradle model type.
[disallowed_types](https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:requirements:disallowed_types)

So, the first commit removed all *sourcesets* references(remove val modifier).

Now second commit actually is not necessary, because I I accidentally deleted the `org.gradle.configuration-cache=true` from compose-resources-gallery

**Comment by storytellerF** [comment]
@Alex009 The configuration-cache of compose-resources-gallery has been enabled.
https://github.com/icerockdev/moko-resources/commit/c0abbcfcf736853ac4785a416696edeff5053dba#diff-c5bc3f5413b74cbba166b46c39ce1293d25af018cd258f7aa5ece60e4b49964aR21

**Comment by Alex009** [comment]
@storytellerF  thanks. 
in #575 gradle plugin was rewritten from scratch and also supports configuration cache, so you can stop work on this request and try to check plugin from #575 in your project. 
i will publish 0.24.0-beta-1 with #575 soon too

**Comment by storytellerF** [comment]
> @storytellerF thanks. in #575 gradle plugin was rewritten from scratch and also supports configuration cache, so you can stop work on this request and try to check plugin from #575 in your project. i will publish 0.24.0-beta-1 with #575 soon too

OK

**Pull request closed without merging**
