### PR TITLE
Fix #118: Fill in missing string translations with base translation

### LINKED ISSUE #118: Add option to fill in missing string translations with base translation
The issue here is what is the fallback behavior if a string does not have a translation. This happens for us because our translation department follows a weekly cadence of updating translations.

For Android it is not an issue. If a translation is missing it just falls back and supplies the base string. For iOS however, it does not fall back to the base string, it falls back to the actual key name. This can have some very weird behavior if for example the string represents a date format.

So I would like a way to tell moko resources to use the base translation if the translation is missing, not the string key. I would turn this on for development. We have a task that will fail release builds for missing translations

### PR DESCRIPTION
**Pull request by colintheshots-meetup**
If no translation is found, we should fallback to the base translation in the default locale for iOS and MacOS.

### CODE REVIEW

**Comment by pkulikowski** [comment]
@Alex009 Is there any plan to add this? We have this issue that on iOS the app does not return a default localization and we have string keys everywhere. @colintheshots-meetup Will this one fix the iOS issue?

**Comment by Alex009** [comment]
> @Alex009 Is there any plan to add this? We have this issue that on iOS the app does not return a default localization and we have string keys everywhere. @colintheshots-meetup Will this one fix the iOS issue?

hi. this pr fix case when you have in base localization more keys than in other languages. with this fix when you try read some key, that not exist in language X but exist in base localization - you got value from base. at now you got just key, as not found.

i think i include this pr in next release (with kotlin 1.9 support)

**Comment by SubhrajyotiSen** [comment]
@Alex009 Is there any pending work on this PR that can push it to get included in the next release? I can work on it if needed

**Comment by Alex009** [comment]
@ExNDY need to add new tests with cases when string/plural have base localization, but not have some language. in this case on language that not localized we should receive text from base localization

**Comment by SubhrajyotiSen** [comment]
@Alex009 I've added test cases for this PR at https://github.com/SubhrajyotiSen/moko-resources/commit/5c453a1310324abad38adc49522ca8a18218b04f

Can you please review these? If they work, feel free to cherry-pick. Otherwise I can open a new PR

**Comment by ExNDY** [comment]
Hi, i'm check this changes on samples and... it doesn't work if you has string in base. I'm find solution of this problem, and my opinion: change your fallback on Base, and after add tests for check.

**Comment by SubhrajyotiSen** [comment]
@ExNDY Does the test at https://github.com/SubhrajyotiSen/moko-resources/commit/5c453a1310324abad38adc49522ca8a18218b04f#diff-bcc9dabae360e0fe619920a8ccedbab18f97381771aa23cf20ce544f1abfb1e6R32 not cover the case you mentioned. The string is present in base but no in another language. 

Or am I missing a case?

**Comment by ExNDY** [comment]
@SubhrajyotiSen sorry, i'm not check this on current time, later tomorrow, i think your brach can help me

**Comment by ExNDY** [comment]
@SubhrajyotiSen thanks for tests.

@Alex009 please check this PR, i think we can include him in release

**Review by Alex009 — APPROVED** [review]

**Pull request merged**
